POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Vídeo 01",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

GET http://localhost:3333/videos?search=node

###
PUT http://localhost:3333/videos/b3b26552-689c-4bdb-9a57-6c4cbd09973a
Content-Type: application/json

{
    "title": "Vídeo 02",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###
DELETE http://localhost:3333/videos/b3b26552-689c-4bdb-9a57-6c4cbd09973a